### ISSUE TITLE
Statistics without link tracking

### ISSUE THREAD

**Issue by lesley-w** [PerplexDigital/PerplexMail-for-Umbraco#7]
Is it possible to have the email statistics without link tracking? Or configure, per email, which links are tracked?

The link tracking creates strange looking urls e.g. 
https://localhost:51137/?i=146&a=click&v=http%3a%2f%2fwww.abcdef.nz

and in some cases e.g. verify email link with token, the link is too long to store in the perplexMailStatistics table as the value field is limited to 255 characters. This causes a string truncation issue when link is clicked - which throws an exception on the site.

**Comment by PerplexWouter** [comment]
Link tracking can be disabled by removing the HTTP module with the name "PerplexMailStatisticsHttpModule" from the web.config. This will stop the package from tracking any links completely and it won't modify the URL's in the e-mail anymore. 
Unfortunately, disabling link tracking for just one link is currently not supported, so it's all or nothing.

Since you are running into string truncation, I recommend simply updating the column 'value' in the table 'perplexMailStatistics' and set the type to NVARCHAR(MAX) to solve this issue. The only design intent was to not store more data than needed, but there is no harm in setting it to MAX.

**Comment by lesley-w** [comment]
@PerplexWouter Thanks for the quick response. Works perfectly.
